/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Classes.DatabaseHandle;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.FileHandler;

/**
 *
 * @author Davi
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToCreateButton = new javax.swing.JButton();
        ToSearchButton = new javax.swing.JButton();
        teamInfo = new javax.swing.JLabel();
        projectTitle = new javax.swing.JLabel();
        deleteTags = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 300));

        ToCreateButton.setLabel("Novo Link");
        ToCreateButton.setMaximumSize(new java.awt.Dimension(80, 24));
        ToCreateButton.setMinimumSize(new java.awt.Dimension(80, 24));
        ToCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToCreateButtonActionPerformed(evt);
            }
        });

        ToSearchButton.setLabel("Buscar Link");
        ToSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToSearchButtonActionPerformed(evt);
            }
        });

        teamInfo.setText("D&D 2015");

        projectTitle.setFont(new java.awt.Font("Quicksand Bold", 0, 48)); // NOI18N
        projectTitle.setText("Project Boot");

        deleteTags.setText("Deletar Tags");
        deleteTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTagsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(teamInfo)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(projectTitle)
                        .addGap(107, 107, 107))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteTags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToSearchButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToCreateButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(projectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ToCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteTags)
                .addGap(26, 26, 26)
                .addComponent(teamInfo)
                .addContainerGap())
        );

        teamInfo.getAccessibleContext().setAccessibleName("Team nfo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToCreateButtonActionPerformed
        this.dispose();
        new TelaAdicionar().setVisible(true);
    }//GEN-LAST:event_ToCreateButtonActionPerformed

    private void ToSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToSearchButtonActionPerformed
        this.dispose();
        new TelaBusca().setVisible(true);
    }//GEN-LAST:event_ToSearchButtonActionPerformed

    private void deleteTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTagsActionPerformed
        ArrayList<Integer> selectedIDs = SelectTags.showTagsForSelection();
        DatabaseHandle dbh = new DatabaseHandle();
        if (selectedIDs != null) {
            for (Integer id : selectedIDs) {
                dbh.deleteTag(id);
            }
        }
    }//GEN-LAST:event_deleteTagsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToCreateButton;
    private javax.swing.JButton ToSearchButton;
    private javax.swing.JButton deleteTags;
    private javax.swing.JLabel projectTitle;
    private javax.swing.JLabel teamInfo;
    // End of variables declaration//GEN-END:variables
}
