/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.table.DefaultTableModel;
import Classes.*;
import java.util.ArrayList;

/**
 *
 * @author Davi
 */
public class TelaBusca extends javax.swing.JFrame {

    /**
     * Creates new form TelaBusca
     */
    public TelaBusca() {
        initComponents();

        populateTable("");
    }
    
    // <editor-fold defaultstate="collapsed" desc="Methods for populating link table">
    private void populateTable(String nameToSearch) {
        DefaultTableModel dtm = new DefaultTableModel();
        String[] header = new String[]{"ID", "Nome", "URL", "Tags", "Comentários", "Criação", "Modificação"};
        dtm.setColumnIdentifiers(header);
        linksTable.setModel(dtm);
        //linksTable.setRowHeight(linksTable.getRowHeight()*2);
        DatabaseHandle dbh = new DatabaseHandle();
        HyperLink[] allLinks = dbh.getLinksByName(nameToSearch);
        if (allLinks != null) {
            for (HyperLink allLink : allLinks) {
                dtm.addRow(new Object[]{allLink.getID(), allLink.getName(), allLink.getURL(), allLink.getAllTags(), allLink.getAllComments(), allLink.getCreationString(), allLink.getModificationString()});
            }
        }
        linksTable.removeColumn(linksTable.getColumnModel().getColumn(0));
    }
    
    private void populateTable(ArrayList<Integer> tagsToFilter) {
        DefaultTableModel dtm = new DefaultTableModel();
        String[] header = new String[]{"Nome", "URL", "Tags", "Comentários", "Criação", "Modificação"};
        dtm.setColumnIdentifiers(header);
        linksTable.setModel(dtm);
        //linksTable.setRowHeight(linksTable.getRowHeight()*2);
        DatabaseHandle dbh = new DatabaseHandle();
        HyperLink[] allLinks;
        if (tagsToFilter != null) {
            allLinks = dbh.getLinksByTags(tagsToFilter);
        } else {
            allLinks = dbh.getAllLinks();
        }
        for (HyperLink allLink : allLinks) {
            dtm.addRow(new Object[]{allLink.getName(), allLink.getURL(), allLink.getAllTags(), allLink.getAllComments(), allLink.getCreationString(), allLink.getModificationString()});
        }
    }
    // </editor-fold>
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterButton = new javax.swing.JButton();
        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        scrollLinks = new javax.swing.JScrollPane();
        linksTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        resetSearch = new javax.swing.JButton();
        searchName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filterButton.setText("Filtrar");
        filterButton.setToolTipText("");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        searchText.setToolTipText("");

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        scrollLinks.setVerifyInputWhenFocusTarget(false);

        linksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        linksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linksTableMouseClicked(evt);
            }
        });
        scrollLinks.setViewportView(linksTable);

        backButton.setText("Voltar");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        resetSearch.setText("Limpar Busca");
        resetSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSearchActionPerformed(evt);
            }
        });

        searchName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchName.setText("Buscar por nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollLinks)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(resetSearch)
                        .addGap(49, 49, 49)
                        .addComponent(filterButton)
                        .addGap(148, 148, 148)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(filterButton)
                    .addComponent(backButton)
                    .addComponent(resetSearch)
                    .addComponent(searchName))
                .addGap(18, 18, 18)
                .addComponent(scrollLinks, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        new TelaInicial().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void resetSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSearchActionPerformed
        populateTable("");
    }//GEN-LAST:event_resetSearchActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String nameToSearch = searchText.getText();
        populateTable(nameToSearch);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        ArrayList<Integer> selectedIDs =  SelectTags.showTagsForSelection();
        populateTable(selectedIDs);
    }//GEN-LAST:event_filterButtonActionPerformed

    private void linksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linksTableMouseClicked
        int id = (int)linksTable.getModel().getValueAt(linksTable.getSelectedRow(),0);
        new TelaEditar(id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_linksTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBusca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton filterButton;
    private javax.swing.JTable linksTable;
    private javax.swing.JButton resetSearch;
    private javax.swing.JScrollPane scrollLinks;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchName;
    private javax.swing.JTextField searchText;
    // End of variables declaration//GEN-END:variables
}
